//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeIDGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FakeIDGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Warszawa
        ///Kraków
        ///Łódź
        ///Wrocław
        ///Poznań
        ///Gdańsk
        ///Szczecin
        ///Bydgoszcz
        ///Lublin
        ///Białystok
        ///Katowice
        ///Gdynia
        ///Częstochowa
        ///Radom
        ///Toruń
        ///Sosnowiec
        ///Kielce
        ///Rzeszów
        ///Gliwice
        ///Zabrze
        ///Olsztyn
        ///Bielsko-Biała
        ///Bytom
        ///Rybnik
        ///Ruda Śląska
        ///Zielona Góra
        ///Tychy
        ///Opole
        ///Gorzów Wielkopolski
        ///Dąbrowa Górnicza
        ///Elbląg
        ///Płock
        ///Wałbrzych
        ///Chorzów
        ///Tarnów
        ///Włocławek
        ///Koszalin
        ///Kalisz
        ///Legnica
        ///Grudziądz
        ///Jaworzno
        ///Jelenia Góra
        ///Siedlce
        ///Inowrocław
        ///Mysłowice
        ///Piotrków Trybunalski
        ///Ostrowiec Świętokrzyski
        ///Gniezno
        ///Suwałki
        ///P [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string cities {
            get {
                return ResourceManager.GetString("cities", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu NOWAK
        ///KOWALSKI
        ///WIŚNIEWSKI
        ///WÓJCIK
        ///KOWALCZYK
        ///KAMIŃSKI
        ///LEWANDOWSKI
        ///ZIELIŃSKI
        ///SZYMAŃSKI
        ///WOŹNIAK
        ///DĄBROWSKI
        ///KOZŁOWSKI
        ///MAZUR
        ///JANKOWSKI
        ///KWIATKOWSKI
        ///WOJCIECHOWSKI
        ///KRAWCZYK
        ///KACZMAREK
        ///PIOTROWSKI
        ///GRABOWSKI
        ///ZAJĄC
        ///PAWŁOWSKI
        ///KRÓL
        ///MICHALSKI
        ///WRÓBEL
        ///WIECZOREK
        ///JABŁOŃSKI
        ///NOWAKOWSKI
        ///MAJEWSKI
        ///OLSZEWSKI
        ///DUDEK
        ///STĘPIEŃ
        ///JAWORSKI
        ///ADAMCZYK
        ///MALINOWSKI
        ///GÓRSKI
        ///PAWLAK
        ///NOWICKI
        ///SIKORA
        ///WITKOWSKI
        ///RUTKOWSKI
        ///WALCZAK
        ///BARAN
        ///MICHALAK
        ///SZEWCZYK
        ///OSTROWSKI
        ///TOMASZEWSKI
        ///ZALEWSKI
        ///WRÓBLEWSKI
        ///PIETRZAK
        ///JASIŃ [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string man_surnames {
            get {
                return ResourceManager.GetString("man_surnames", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ada
        ///Adalbert
        ///Adam
        ///Adela
        ///Adelajda
        ///Adrian
        ///Aga
        ///Agata
        ///Agnieszka
        ///Albert
        ///Alberta
        ///Aldona
        ///Aleksander
        ///Aleksandra
        ///Alfred
        ///Alicja
        ///Alina
        ///Amadeusz
        ///Ambroży
        ///Amelia
        ///Anastazja
        ///Anastazy
        ///Anatol
        ///Andrzej
        ///Aneta
        ///Angelika
        ///Angelina
        ///Aniela
        ///Anita
        ///Anna
        ///Antoni
        ///Antonina
        ///Anzelm
        ///Apolinary
        ///Apollo
        ///Apolonia
        ///Apoloniusz
        ///Ariadna
        ///Arkadiusz
        ///Arkady
        ///Arlena
        ///Arleta
        ///Arletta
        ///Arnold
        ///Arnolf
        ///August
        ///Augustyna
        ///Aurela
        ///Aurelia
        ///Aurelian
        ///Aureliusz
        ///Balbina
        ///Baltazar
        ///Barbara
        ///Bartłomiej
        ///Bartosz
        ///Bazyli
        ///Beata
        ///Benedykt
        ///Benedykta
        ///Beniamin
        ///Bernadeta
        ///Bernard
        ///Bernardeta
        ///Be [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string names_a {
            get {
                return ResourceManager.GetString("names_a", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adalbert
        ///Adam
        ///Adrian
        ///Albert
        ///Aleksander
        ///Alfred
        ///Amadeusz
        ///Ambroży
        ///Anastazy
        ///Anatol
        ///Andrzej
        ///Antoni
        ///Anzelm
        ///Apolinary
        ///Apollo
        ///Apoloniusz
        ///Arkadiusz
        ///Arkady
        ///Arnold
        ///Arnolf
        ///August
        ///Aurelian
        ///Aureliusz
        ///Baltazar
        ///Bartłomiej
        ///Bartosz
        ///Bazyli
        ///Benedykt
        ///Beniamin
        ///Bernard
        ///Bernardyn
        ///Błażej
        ///Bogdan
        ///Bogumił
        ///Bogusław
        ///Bohdan
        ///Bolesław
        ///Bronisław
        ///Broniszław
        ///Brunon
        ///Cecyl
        ///Celestyn
        ///Cezary
        ///Cyprian
        ///Cyryl
        ///Damian
        ///Daniel
        ///Dariusz
        ///Dawid
        ///Dominik
        ///Dorian
        ///Dymitr
        ///Edmund
        ///Edward
        ///Edwin
        ///Egon
        ///Eliasz
        ///Eligi [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string names_m {
            get {
                return ResourceManager.GetString("names_m", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ada
        ///Adela
        ///Adelajda
        ///Aga
        ///Agata
        ///Agnieszka
        ///Alberta
        ///Aldona
        ///Aleksandra
        ///Alicja
        ///Alina
        ///Amelia
        ///Anastazja
        ///Aneta
        ///Angelika
        ///Angelina
        ///Aniela
        ///Anita
        ///Anna
        ///Antonina
        ///Apolonia
        ///Ariadna
        ///Arlena
        ///Arleta
        ///Arletta
        ///Augustyna
        ///Aurela
        ///Aurelia
        ///Balbina
        ///Barbara
        ///Beata
        ///Benedykta
        ///Bernadeta
        ///Bernardeta
        ///Bernardyna
        ///Bogdana
        ///Bogna
        ///Bogumiła
        ///Bogusława
        ///Bonawentura
        ///Bożena
        ///Bronisława
        ///Brygida
        ///Cecylia
        ///Celestyna
        ///Celina
        ///Dalia
        ///Daniela
        ///Danuta
        ///Daria
        ///Diana
        ///Dianna
        ///Dobrawa
        ///Dominika
        ///Donata
        ///Dorota
        ///Edyta
        ///Eleonora [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string names_w {
            get {
                return ResourceManager.GetString("names_w", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu NOWAK
        ///KOWALSKA
        ///WIŚNIEWSKA
        ///WÓJCIK
        ///KOWALCZYK
        ///KAMIŃSKA
        ///LEWANDOWSKA
        ///ZIELIŃSKA
        ///SZYMAŃSKA
        ///DĄBROWSKA
        ///WOŹNIAK
        ///KOZŁOWSKA
        ///JANKOWSKA
        ///MAZUR
        ///KWIATKOWSKA
        ///WOJCIECHOWSKA
        ///KRAWCZYK
        ///KACZMAREK
        ///PIOTROWSKA
        ///GRABOWSKA
        ///PAWŁOWSKA
        ///MICHALSKA
        ///KRÓL
        ///ZAJĄC
        ///WIECZOREK
        ///JABŁOŃSKA
        ///WRÓBEL
        ///NOWAKOWSKA
        ///MAJEWSKA
        ///OLSZEWSKA
        ///ADAMCZYK
        ///JAWORSKA
        ///MALINOWSKA
        ///STĘPIEŃ
        ///DUDEK
        ///GÓRSKA
        ///NOWICKA
        ///WITKOWSKA
        ///PAWLAK
        ///SIKORA
        ///WALCZAK
        ///RUTKOWSKA
        ///MICHALAK
        ///SZEWCZYK
        ///OSTROWSKA
        ///BARAN
        ///TOMASZEWSKA
        ///ZALEWSKA
        ///PIETRZAK
        ///WRÓBLEWSKA
        ///JASIŃ [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string woman_surnames {
            get {
                return ResourceManager.GetString("woman_surnames", resourceCulture);
            }
        }
    }
}
